/*
Write  a  multithreaded  program  that  generates  the  Fibonacci  series.  The  program  should 
work as follows: The user will enter on the command line the number of Fibonacci numbers 
that  the  program  is  to  generate.  The  program  then  will  create  a  separate  thread  that  will 
generate the Fibonacci numbers, placing the sequence in data that is shared by the threads 
(an  array  is  probably  the  most  convenient  data  structure).  When  the  thread  finishes 
execution the parent will output the sequence generated by the child thread. Because the 
parent thread cannot begin outputting the Fibonacci sequence until the child thread finishes, 
this will require having the parent thread wait for the child thread to finish.
*/

#include<pthread.h>
#include<stdio.h>
#include<stdlib.h>
int n,*f;
void* gen(void* a){
    f[0]=0;
    f[1]=1;
    for(int i=2;i<n;i++)
        f[i]=f[i-1]+f[i-2];
    return NULL;
}
int main(int c,char** v){
    if(c<2){
        printf("Usage: %s <n>\n",v[0]);
        return 1;
    }
    n=atoi(v[1]);
    f=malloc(n*sizeof(int));
    pthread_t t;
    pthread_create(&t,0,gen,0);
    pthread_join(t,0);
    for(int i=0;i<n;i++)
        printf("%d ",f[i]);
    printf("\n");
    free(f);
    return 0;
}

/*
output:
$ ./1.out 10
0 1 1 2 3 5 8 13 21 34
*/